#!/bin/sh

set -e

if [ ! -f /home/jovyan/.ssh/id_rsa ] ; then
  exit
fi

echo "➜ Connecting to controller"

CONTROLLER_HOST=`echo $CONTROLLER | cut -d: -f1`
CONTROLLER_PORT=`echo $CONTROLLER | cut -d: -f2`

security="/home/jovyan/.ipython/profile_default/security"
scp -P $CONTROLLER_PORT $CONTROLLER_HOST:$security/* $security

ports=`cat ${security}/*.json | sed -En "s/.*: ([0-9]+),?/\1/p" | sort | uniq`

ssh_tunnels=""
for p in `echo $ports`; do
  ssh_tunnels="${ssh_tunnels} -L ${p}:localhost:${p}"
done

ssh -f -N $ssh_tunnels $CONTROLLER_HOST -p $CONTROLLER_PORT
