#!/bin/sh

echo "➜ SSH server"
mkdir -p /home/jovyan/sshd
ssh-keygen -q -t rsa -N '' -f /home/jovyan/sshd/host_key

cat << EOF > /home/jovyan/sshd/sshd_config
Port 2222
Protocol 2
UsePrivilegeSeparation no
HostKey /home/jovyan/sshd/host_key
PidFile /home/jovyan/sshd/pid
EOF

/usr/sbin/sshd -f /home/jovyan/sshd/sshd_config -E /home/jovyan/sshd/log

echo "➜ Starting up controller"
exec ipcontroller --location='127.0.0.1' \
                  --no-secure
