#!/bin/sh

/docker-scripts/controller-connect

echo "➜ Starting up notebook server"

echo "c.NotebookApp.server_extensions.append('ipyparallel.nbextension')" \
  > /home/jovyan/.jupyter/jupyter_notebook_config.py

exec jupyter notebook --ip='*'
