#!/bin/bash

echo "➜ Setting up jovyan user"

USER_ID=`echo $JUPYTER_ID | cut -d: -f1`
GROUP_ID=`echo $JUPYTER_ID | cut -d: -f2`

useradd --create-home -s /bin/bash -u $USER_ID jovyan
if [ "$GROUP_ID" != $(id -g jovyan) ] ; then
  groupmod -g $GROUP_ID jovyan
fi

# Enable sudo if requested
if [ ! -z "$GRANT_SUDO" ]; then
  echo "➜ Adding jovyan to sudoers"
  echo "jovyan ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
fi

cd /home/jovyan

# Pass on SSH keys
mkdir .ssh
if [ -f /id_rsa ] || [ -f /id_rsa.pub ]; then
  cp /id_rsa* .ssh
fi

# Import pre-built ipython profile
cp -R /root/.ipython .ipython

# Setting permissions
chown -R jovyan:jovyan /home/jovyan

# Dispatch docker command
exec su jovyan /docker-commands/$@
