#!/bin/bash

set -e

echo "➜ Setting up user"

USER_NAME=$(echo $JUPYTER_ID | cut -d: -f1)
USER_ID=$(echo $JUPYTER_ID | cut -d: -f2)
GROUP_ID=$(echo $JUPYTER_ID | cut -d: -f3)

groupadd -o -g $GROUP_ID $USER_NAME
useradd --create-home -s /bin/bash -u $USER_ID -g $GROUP_ID $USER_NAME

# Enable sudo if requested
if [ ! -z $JUPYTER_SUDO ]; then
  echo "➜ Adding user to sudoers"
  echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
fi

cd /home/$USER_NAME

# Pass on SSH keys
mkdir .ssh
if [ -f /id_rsa ] || [ -f /id_rsa.pub ]; then
  cp /id_rsa* .ssh
fi
chown -R $USER_NAME:$USER_NAME .ssh

# Dispatch docker command
exec su $USER_NAME /docker-commands/$*
