#!/bin/sh

set -e

# Pass either "*", engine or client
FILTER=$1

if [ -z $JUPYTER_CONTROLLER ] || [ ! -f $HOME/.ssh/id_rsa ] ; then
  exit
fi

echo "➜ Connecting to controller"
CONTROLLER_HOST=$(echo $JUPYTER_CONTROLLER | cut -d: -f1)
CONTROLLER_PORT=$(echo $JUPYTER_CONTROLLER | cut -d: -f2)

# Enable password-less SSH connections
cat << __EOF__ > $HOME/.ssh/config
Host $CONTROLLER_HOST
    StrictHostKeyChecking no
__EOF__

# Retrieve ipyparallel connection files
ipython profile create --parallel --log-level=ERROR
DIR="$HOME/.ipython/profile_default/security"
scp -P $CONTROLLER_PORT $CONTROLLER_HOST:$DIR/ipcontroller-$FILTER.json $DIR

# Build tunnels
PORTS=$(cat $DIR/*.json | sed -En "s/.*: ([0-9]+),?/\1/p" | sort | uniq)
TUNNELS=""
for x in $PORTS; do
  TUNNELS="$TUNNELS -L $x:127.0.0.1:$x"
done
ssh -fNT $TUNNELS -p $CONTROLLER_PORT $CONTROLLER_HOST
