#!/bin/sh

/docker-commands/controller-connect

echo "➜ Starting up notebook server"

mkdir .jupyter
echo "c.NotebookApp.server_extensions.append('ipyparallel.nbextension')" \
  > .jupyter/jupyter_notebook_config.py

exec jupyter notebook --ip='*'
